workflows:
  ios-release:
    name: Build iOS IPA

    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest

      ios_signing:
        distribution_type: development
        bundle_identifier: com.pansieri.app

    scripts:
      - flutter pub get
      - flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa